version: '3'

services:
  postgres:
    image: postgres:11
    ports:
      - "25432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: distedavim-auth-task-db
    volumes:
      - postgres-db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distedavim-auth-task
    env_file:
      - .env
    ports:
      - '8002:8002'
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - ./src:/app/src

volumes:
  postgres-db: